2021-06-03 22:23:41,695 root ERROR Something went wrong: 1050 (42S01): Table 'test' already exists
2021-06-03 22:23:41,699 werkzeug INFO 127.0.0.1 - - [03/Jun/2021 22:23:41] "[37mPOST /create HTTP/1.1[0m" 200 -
2021-06-03 23:29:32,695 root ERROR Something went wrong: 1050 (42S01): Table 'test' already exists
2021-06-03 23:29:32,696 app ERROR Exception on /create [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2021-06-03 23:29:32,699 werkzeug INFO 127.0.0.1 - - [03/Jun/2021 23:29:32] "[35m[1mPOST /create HTTP/1.1[0m" 500 -
2021-06-03 23:30:09,005 root ERROR Something went wrong: 1050 (42S01): Table 'test' already exists
2021-06-03 23:30:09,006 app ERROR Exception on /create [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2021-06-03 23:30:09,007 werkzeug INFO 127.0.0.1 - - [03/Jun/2021 23:30:09] "[35m[1mPOST /create HTTP/1.1[0m" 500 -
2021-06-03 23:30:37,575 root ERROR Something went wrong: 1050 (42S01): Table 'test' already exists
2021-06-03 23:30:37,577 app ERROR Exception on /create [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2021-06-03 23:30:37,578 werkzeug INFO 127.0.0.1 - - [03/Jun/2021 23:30:37] "[35m[1mPOST /create HTTP/1.1[0m" 500 -
2021-06-03 23:31:22,425 root ERROR Something went wrong: 1050 (42S01): Table 'test' already exists
2021-06-03 23:31:22,427 app ERROR Exception on /create [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2021-06-03 23:31:22,428 werkzeug INFO 127.0.0.1 - - [03/Jun/2021 23:31:22] "[35m[1mPOST /create HTTP/1.1[0m" 500 -
2021-06-03 23:33:23,634 root ERROR Something went wrong: 1050 (42S01): Table 'test' already exists
2021-06-03 23:33:23,635 app ERROR Exception on /create [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2021-06-03 23:33:23,637 werkzeug INFO 127.0.0.1 - - [03/Jun/2021 23:33:23] "[35m[1mPOST /create HTTP/1.1[0m" 500 -
2021-06-03 23:33:51,731 root ERROR Something went wrong: 1050 (42S01): Table 'test' already exists
2021-06-03 23:33:51,733 app ERROR Exception on /create [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2021-06-03 23:33:51,734 werkzeug INFO 127.0.0.1 - - [03/Jun/2021 23:33:51] "[35m[1mPOST /create HTTP/1.1[0m" 500 -
2021-06-03 23:34:24,095 root ERROR Something went wrong: 1050 (42S01): Table 'test' already exists
2021-06-03 23:34:24,097 app ERROR Exception on /create [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2021-06-03 23:34:24,099 werkzeug INFO 127.0.0.1 - - [03/Jun/2021 23:34:24] "[35m[1mPOST /create HTTP/1.1[0m" 500 -
2021-06-03 23:36:00,116 root ERROR Something went wrong: 1050 (42S01): Table 'test' already exists
2021-06-03 23:36:00,127 werkzeug INFO 127.0.0.1 - - [03/Jun/2021 23:36:00] "[35m[1mPOST /create HTTP/1.1[0m" 500 -
2021-06-03 23:38:18,436 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\dbOperations.py', reloading
2021-06-03 23:38:18,438 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\dbOperations.py', reloading
2021-06-03 23:38:18,439 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\dbOperations.py', reloading
2021-06-03 23:38:18,441 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\dbOperations.py', reloading
2021-06-03 23:38:25,558 root ERROR Something went wrong: 1050 (42S01): Table 'test' already exists
2021-06-03 23:38:25,570 werkzeug INFO 127.0.0.1 - - [03/Jun/2021 23:38:25] "[35m[1mPOST /create HTTP/1.1[0m" 500 -
2021-06-03 23:39:01,644 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\dbOperations.py', reloading
2021-06-03 23:39:01,646 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\dbOperations.py', reloading
2021-06-03 23:39:01,648 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\dbOperations.py', reloading
2021-06-03 23:39:01,649 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\dbOperations.py', reloading
2021-06-03 23:39:09,814 root ERROR Something went wrong: 1050 (42S01): Table 'test' already exists
2021-06-03 23:39:09,826 werkzeug INFO 127.0.0.1 - - [03/Jun/2021 23:39:09] "[35m[1mPOST /create HTTP/1.1[0m" 500 -
2021-06-03 23:39:35,644 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\dbOperations.py', reloading
2021-06-03 23:39:35,645 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\dbOperations.py', reloading
2021-06-03 23:39:35,671 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\dbOperations.py', reloading
2021-06-03 23:39:35,672 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\dbOperations.py', reloading
2021-06-03 23:39:49,824 root ERROR Something went wrong: 1050 (42S01): Table 'test' already exists
2021-06-03 23:39:49,834 werkzeug INFO 127.0.0.1 - - [03/Jun/2021 23:39:49] "[35m[1mPOST /create HTTP/1.1[0m" 500 -
2021-06-03 23:41:01,675 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\app.py', reloading
2021-06-03 23:41:01,693 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\app.py', reloading
2021-06-03 23:41:09,841 root ERROR Something went wrong: 1050 (42S01): Table 'test' already exists
2021-06-03 23:41:09,853 werkzeug INFO 127.0.0.1 - - [03/Jun/2021 23:41:09] "[35m[1mPOST /create HTTP/1.1[0m" 500 -
2021-06-03 23:41:39,491 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\app.py', reloading
2021-06-03 23:41:39,517 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\app.py', reloading
2021-06-03 23:41:44,242 root ERROR Something went wrong: 1050 (42S01): Table 'test' already exists
2021-06-03 23:41:44,249 werkzeug INFO  * Detected change in 'C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\flask\\app.py', reloading
2021-06-03 23:41:44,252 werkzeug INFO  * Detected change in 'C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\flask\\_compat.py', reloading
2021-06-03 23:41:44,255 werkzeug INFO 127.0.0.1 - - [03/Jun/2021 23:41:44] "[35m[1mPOST /create HTTP/1.1[0m" 500 -
2021-06-03 23:41:55,978 root ERROR Something went wrong: 1050 (42S01): Table 'test' already exists
2021-06-03 23:41:55,989 werkzeug INFO 127.0.0.1 - - [03/Jun/2021 23:41:55] "[35m[1mPOST /create HTTP/1.1[0m" 500 -
2021-06-03 23:42:26,828 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\app.py', reloading
2021-06-03 23:42:26,840 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\app.py', reloading
2021-06-03 23:42:27,170 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\app.py', reloading
2021-06-03 23:42:27,184 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\app.py', reloading
2021-06-03 23:42:32,861 root ERROR Something went wrong: 1050 (42S01): Table 'test' already exists
2021-06-03 23:42:32,873 werkzeug INFO 127.0.0.1 - - [03/Jun/2021 23:42:32] "[35m[1mPOST /create HTTP/1.1[0m" 500 -
2021-06-03 23:42:43,329 root ERROR Something went wrong: 1050 (42S01): Table 'test' already exists
2021-06-03 23:42:43,340 werkzeug INFO 127.0.0.1 - - [03/Jun/2021 23:42:43] "[35m[1mPOST /create HTTP/1.1[0m" 500 -
2021-06-03 23:42:51,722 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\queryDetails.py', reloading
2021-06-03 23:42:51,729 werkzeug INFO 127.0.0.1 - - [03/Jun/2021 23:42:51] "[35m[1mPOST /create HTTP/1.1[0m" 500 -
2021-06-03 23:42:57,399 root ERROR Something went wrong: 1050 (42S01): Table 'test' already exists
2021-06-03 23:42:57,411 werkzeug INFO 127.0.0.1 - - [03/Jun/2021 23:42:57] "[35m[1mPOST /create HTTP/1.1[0m" 500 -
2021-06-03 23:43:35,683 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\app.py', reloading
2021-06-03 23:43:35,804 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\app.py', reloading
2021-06-03 23:43:58,126 root ERROR Something went wrong: 1050 (42S01): Table 'test' already exists
2021-06-03 23:43:58,138 werkzeug INFO 127.0.0.1 - - [03/Jun/2021 23:43:58] "[35m[1mPOST /create HTTP/1.1[0m" 500 -
2021-06-03 23:45:23,043 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\app.py', reloading
2021-06-03 23:45:23,080 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\app.py', reloading
2021-06-03 23:45:27,056 root ERROR Something went wrong: 1050 (42S01): Table 'test' already exists
2021-06-03 23:45:27,058 werkzeug INFO 127.0.0.1 - - [03/Jun/2021 23:45:27] "[37mPOST /create HTTP/1.1[0m" 200 -
2021-06-03 23:45:37,988 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\app.py', reloading
2021-06-03 23:46:01,967 root ERROR Something went wrong: 1050 (42S01): Table 'test' already exists
2021-06-03 23:46:01,969 werkzeug INFO 127.0.0.1 - - [03/Jun/2021 23:46:01] "[37mPOST /create HTTP/1.1[0m" 200 -
2021-06-04 00:02:01,453 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\app.py', reloading
2021-06-04 00:02:01,454 werkzeug INFO  * Detected change in 'C:\\Users\\motheesh jay\\Documents\\data_science\\ineuron\\Flask\\MyProject\\app.py', reloading
